<a href="https://colab.research.google.com/github/cloud1work1/numpy-tutorial/blob/main/Numpy_tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [ ]:
x = np.array([1,3,4,5,6])
x

array([1, 3, 4, 5, 6])

In [ ]:
r = np.random.randint(2,10)
r

4

In [ ]:
sample = np.random.randint(0,12,100)
%timeit np.power(sample,2)

The slowest run took 29.95 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 3: 1.21 µs per loop


In [ ]:
%timeit list(np.power(sample,2))

The slowest run took 4.75 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 3: 11.3 µs per loop


In [ ]:
np.__version__

'1.19.5'

In [ ]:
import numpy as np

In [ ]:
x = np.array([1,2,3,4])

In [ ]:
x

array([1, 2, 3, 4])

In [ ]:
s=np.random.randint(2,10)
s

9

In [ ]:
t=np.random.randint(2,100,2000)
%timeit np.power(t,2)

The slowest run took 155.30 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 3: 5.76 µs per loop


In [ ]:
%timeit list(np.power(t,2))

10000 loops, best of 3: 173 µs per loop


In [ ]:
np.__version__

'1.19.5'

In [4]:
# define array
mylist = [1,3,5]
myarray = np.array(mylist)
myarray.shape

(3,)

In [7]:
# access values
mylist = [[1,2,3], [7,8,4]]
myarray = np.array(mylist)
print(myarray[0])
print(myarray[-1])
print(myarray[0,2])
print(myarray[:,1])

[1 2 3]
[7 8 4]
3
[2 8]


In [9]:
# arithmetic
myarray1 = np.array([2, 2, 2])
myarray2 = np.array([3, 3, 3])
print(myarray1+myarray2)
print(myarray1*myarray2)

[5 5 5]
[6 6 6]
