<a href="https://colab.research.google.com/github/cloud1work1/numpy-tutorial/blob/main/Numpy_tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [ ]:
x = np.array([1,3,4,5,6])
x

array([1, 3, 4, 5, 6])

In [ ]:
r = np.random.randint(2,10)
r

4

In [ ]:
sample = np.random.randint(0,12,100)
%timeit np.power(sample,2)

The slowest run took 29.95 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 3: 1.21 µs per loop


In [ ]:
%timeit list(np.power(sample,2))

The slowest run took 4.75 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 3: 11.3 µs per loop


In [ ]:
np.__version__

'1.19.5'

In [ ]:
import numpy as np

In [ ]:
x = np.array([1,2,3,4])

In [ ]:
x

array([1, 2, 3, 4])

In [ ]:
s=np.random.randint(2,10)
s

9

In [ ]:
t=np.random.randint(2,100,2000)
%timeit np.power(t,2)

The slowest run took 155.30 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 3: 5.76 µs per loop


In [ ]:
%timeit list(np.power(t,2))

10000 loops, best of 3: 173 µs per loop


In [ ]:
np.__version__

'1.19.5'

In [ ]:
# define array
mylist = [1,3,5]
myarray = np.array(mylist)
myarray.shape

(3,)

In [ ]:
# access values
mylist = [[1,2,3], [7,8,4]]
myarray = np.array(mylist)
print(myarray[0])
print(myarray[-1])
print(myarray[0,2])
print(myarray[:,1])

[1 2 3]
[7 8 4]
3
[2 8]


In [ ]:
# arithmetic
myarray1 = np.array([2, 2, 2])
myarray2 = np.array([3, 3, 3])
print(myarray1+myarray2)
print(myarray1*myarray2)

[5 5 5]
[6 6 6]


In [ ]:
# *Dimension*

In [ ]:
x=np.array(12)
print(x.ndim)
x1=np.array([1,2,4])
print(x1.ndim)
x1=np.array([[1,2,4]])
print(x1.ndim)
x1=np.array([[[1,2,4]]])
print(x1.ndim)
#setting dimension while creation
y = np.array([1,2,3,4,5], ndmin=5)
print(y)
print(y.ndim)

0
1
2
3
[[[[[1 2 3 4 5]]]]]
5


In [3]:
# *Shape*
x=np.array(12)
print(x.shape)
x1=np.array([1,2,4])
print(x1.shape)
x1=np.array([[1,2,4]])
print(x1.shape)
x1=np.array([[[1,2,4]]])
print(x1.shape)
#modifying shape
x1.shape=(3,1)
print(x1)

()
(3,)
(1, 3)
(1, 1, 3)
[[1]
 [2]
 [4]]


In [8]:
arr =np.array([[[1,2,3],[4,5,6]], [[7,8,9],[10,11,12]]])
arr.shape

(2, 2, 3)

In [5]:
arr.ndim

3

In [9]:
#use of nditer
for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6
7
8
9
10
11
12


In [11]:
#use of np.ndenumerate
for i, x in np.ndenumerate(arr):
  print(i,x)

(0, 0, 0) 1
(0, 0, 1) 2
(0, 0, 2) 3
(0, 1, 0) 4
(0, 1, 1) 5
(0, 1, 2) 6
(1, 0, 0) 7
(1, 0, 1) 8
(1, 0, 2) 9
(1, 1, 0) 10
(1, 1, 1) 11
(1, 1, 2) 12
